// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnvrjaepddkpapdtetyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhudnJqYWVwZGRrcGFwZHRldHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjQzMzQsImV4cCI6MjA1NzIwMDMzNH0.VbnF3IPeALNiuZakFDCMPVw56idbUmO6Dqzfc0fZXOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);